spring.application.name=linesOfAction

server.tomcat.threads.max=200
server.connection-timeout=5s
server.max-http-request-header-size=40KB
server.tomcat.max-swallow-size=2MB
server.tomcat.max-http-post-size=2MB

spring.thymeleaf.cache=false
logging.level.org.thymeleaf=DEBUG

spring.data.mongodb.host=dev-cluster.ia4eq.mongodb.net
spring.data.mongodb.port=27017
spring.data.mongodb.database=live_play
spring.data.mongodb.username=seanmclennanqa
spring.data.mongodb.password=cfugUUCX7ixbHJZ8
